name: dev-ci-backend

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  auth-build-deploy:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # 1) Auth to Google with WIF
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.BE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.BE_SA_EMAIL }}
          project_id: ${{ vars.BE_PROJECT_ID }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3

      # 2) Apply Terraform to provision/refresh infra (uses remote state)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Apply (infra)
        working-directory: terraform/
        env:
          TF_VAR_fe_project_id: ${{ vars.FE_PROJECT_ID }}
          TF_VAR_fe_region: ${{ vars.FE_REGION }}
          TF_VAR_fe_project_num: ${{ vars.FE_PROJECT_NUM }}
          TF_VAR_my_domain: ${{ vars.MY_DOMAIN }}
          TF_VAR_my_user: ${{ vars.MY_USER }}
          TF_VAR_be_project_id: ${{ vars.BE_PROJECT_ID }}
          TF_VAR_be_region: ${{ vars.BE_REGION }}
          TF_VAR_be_project_num: ${{ vars.BE_PROJECT_NUM }}
          TF_VAR_gh_backend_repo: ${{ vars.GH_BACKEND_REPO }}
          TF_VAR_gh_frontend_repo: ${{ vars.GH_FRONTEND_REPO }}
        run: |
          terraform init -input=false -reconfigure
          terraform apply -input=false -auto-approve

      # 3) Build & push container image to Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.AR_LOCATION }}-docker.pkg.dev --quiet

      - name: Build & Push
        env:
          IMAGE: ${{ vars.AR_LOCATION }}-docker.pkg.dev/${{ vars.BE_PROJECT_ID }}/${{ vars.AR_REPOSITORY }}/backend:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" app/
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 4) Deploy to Cloud Run (gcloud)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.RUN_SERVICE }} \
            --region ${{ vars.BE_REGION }} \
            --platform managed \
            --image "$IMAGE" \
            --quiet \
            --set-env-vars LOG_LEVEL=info

      - name: Show service URL
        run: |
          gcloud run services describe ${{ vars.RUN_SERVICE }} --region ${{ vars.BE_REGION }} --format='value(status.url)'